### ISSUE TITLE
[Bug Report]: Unable to build bicep-registry-modules on Azure DevOps Agent

### ISSUE THREAD

**Issue by dciborow** [Azure/bicep-registry-modules#171]
### Module path

/modules/*

### Bicep version

0.10.61

### Describe the bug

The issue reported here has forced me to remove all usage of bicep-registry-modules from my main project.
https://github.com/Azure/bicep/issues/6500

This appears to  occur on Linux VMs in Azure DevOps (but not Windows VMs)

### To reproduce

I have a commit which fixes the issue here. https://msazure.visualstudio.com/One/_git/Azure-Gaming/commit/2062694455a6b7cb4ba17779e04c4187bca7a5a3?refName=refs%2Fheads%2Fdciborow%2Fdeploy-arm

We can use this to create a new PR to reproduce. 

### Relevant log output

```Shell
at Bicep.Core.TypeSystem.TypeAssignmentVisitor.<>c__DisplayClass21_0.<VisitModuleDeclarationSyntax>b__0(IDiagnosticWriter diagnostics)
   at Bicep.Core.TypeSystem.TypeAssignmentVisitor.<>c__DisplayClass15_0.<AssignTypeWithDiagnostics>b__0()
   at Bicep.Core.TypeSystem.TypeAssignmentVisitor.<>c__DisplayClass13_0.<AssignTypeWithCaching>b__0(SyntaxBase key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey , Func`2 )
   at Bicep.Core.TypeSystem.TypeAssignmentVisitor.AssignTypeWithCaching(SyntaxBase syntax, Func`1 assignFunc)
   at Bicep.Core.TypeSystem.TypeAssignmentVisitor.AssignTypeWithDiagnostics(SyntaxBase syntax, Func`2 assignFunc)
   at Bicep.Core.TypeSystem.TypeAssignmentVisitor.VisitModuleDeclarationSyntax(ModuleDeclarationSyntax syntax)
   at Bicep.Core.Syntax.ModuleDeclarationSyntax.Accept(ISyntaxVisitor visitor)
   at Bicep.Core.Syntax.SyntaxVisitor.VisitInternal(SyntaxBase node)
   at Bicep.Core.Syntax.SyntaxVisitor.Visit(SyntaxBase node)
   at Bicep.Core.TypeSystem.TypeAssignmentVisitor.GetTypeAssignment(SyntaxBase syntax)
   at Bicep.Core.TypeSystem.TypeAssignmentVisitor.GetTypeInfo(SyntaxBase syntax)
   at Bicep.Core.TypeSystem.TypeManager.GetTypeInfo(SyntaxBase syntax)
   at Bicep.Core.Semantics.DeclaredSymbol.get_Type()
   at Bicep.Core.Semantics.ModuleSymbol.get_Descendants()+MoveNext()
   at Bicep.Core.Semantics.SymbolVisitor.VisitDescendants(Symbol symbol)
   at Bicep.Core.Semantics.SymbolVisitor.VisitModuleSymbol(ModuleSymbol symbol)
   at Bicep.Core.Semantics.SemanticDiagnosticVisitor.VisitModuleSymbol(ModuleSymbol symbol)
   at Bicep.Core.Semantics.ModuleSymbol.Accept(SymbolVisitor visitor)
   at Bicep.Core.Semantics.SymbolVisitor.VisitInternal(Symbol node)
   at Bicep.Core.Semantics.SymbolVisitor.VisitDescendants(Symbol symbol)
   at Bicep.Core.Semantics.SymbolVisitor.VisitFileSymbol(FileSymbol symbol)
   at Bicep.Core.Semantics.SemanticDiagnosticVisitor.VisitFileSymbol(FileSymbol symbol)
   at Bicep.Core.Semantics.FileSymbol.Accept(SymbolVisitor visitor)
   at Bicep.Core.Semantics.SemanticModel.GetSemanticDiagnostics()
   at Bicep.Core.Semantics.SemanticModel.AssembleDiagnostics()
   at Bicep.Core.Semantics.SemanticModel.<.ctor>b__8_5()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode )
   at System.Lazy`1.ExecutionAndPublication(LazyHelper , Boolean )
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Bicep.Core.Semantics.SemanticModel.GetAllDiagnostics()
   at Bicep.Core.Semantics.Compilation.<GetAllDiagnosticsByBicepFile>b__21_1(BicepFile bicepFile)
   at System.Collections.Immutable.ImmutableDictionary.<>c__DisplayClass9_0`3.<ToImmutableDictionary>b__0(TSource )
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 , MutationInput , KeyCollisionBehavior )
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 , Boolean )
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 )
   at System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionary[TSource,TKey,TValue](IEnumerable`1 , Func`2 , Func`2 , IEqualityComparer`1 , IEqualityComparer`1 )
   at System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionary[TSource,TKey,TValue](IEnumerable`1 , Func`2 , Func`2 )
   at Bicep.Core.Semantics.Compilation.GetAllDiagnosticsByBicepFile()
   at Bicep.Cli.Services.CompilationService.LogDiagnostics(Compilation compilation)
   at Bicep.Cli.Services.CompilationService.CompileAsync(Uri inputUri, Boolean skipRestore)
   at Bicep.Cli.Services.CompilationService.CompileAsync(String inputPath, Boolean skipRestore)
   at Bicep.Cli.Commands.BuildCommand.RunAsync(BuildArguments args)
   at Bicep.Cli.Program.RunAsync(String[] args)
   at Bicep.Cli.Program.Main(String[] args)
   at Bicep.Cli.Program.<Main>(String[] args)
```

**Comment by StuffNL** [comment]
I'm having exactly the same issue. Works on my machine, but not in my CI/CD pipeline.

**Comment by shenglol** [comment]
Close as a dup of https://github.com/Azure/bicep/issues/6500.
