### ISSUE TITLE
[AVM Module Issue]: res/web/site not appending EndpointSuffix to AzureWebJobsStorage

### ISSUE THREAD

**Issue by sindkor** [Azure/bicep-registry-modules#2483]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/web/site

### (Optional) Module Version

0.3.7

### Description

Using the following module call:

```bicep
module function 'br/public:avm/res/web/site:0.3.7' = {
  name: '${functionName}-deployment'

  dependsOn: [
    storage
  ]

  params: {
    name: functionName
    location: location
    
    kind: 'functionapp,linux'
    serverFarmResourceId: asp.outputs.resourceId
    appInsightResourceId: appInsights.outputs.resourceId
    storageAccountResourceId: storage.outputs.resourceId

    managedIdentities: {
      systemAssigned: true
    }

    siteConfig: {
      alwaysOn: false
    }

    appSettingsKeyValuePairs: {
      FUNCTIONS_EXTENSION_VERSION: '~4'
      FUNCTIONS_WORKER_RUNTIME: 'java'
      AZURE_FUNCTIONS_ENVIRONMENT: environmentName == 'prod' ? 'Production' : 'Development'
      FUNCTION_APP_EDIT_MODE: 'readonly'
      WEBSITE_CONTENTAZUREFILECONNECTIONSTRING: storageAccountConnectionString
      WEBSITE_CONTENTSHARE: functionName
    }
  }
}
```

I've set Java version 17 and OS as Linux in pom.xml.

The module sets the app setting/environment variable `AzureWebJobsStorage` as expected. However, it does not append `EndpointSuffix=core.windows.net`. This leads to the following error when trying to deploy to the function using the Github Action `Azure/functions-action`:

```
Error: Invalid EndpointSuffix in the provided Connection String
    at extractConnectionStringParts (/home/runner/work/_actions/Azure/functions-action/v1/node_modules/@azure/storage-blob/dist/index.js:13685:23)
    at BlobServiceClient.fromConnectionString (/home/runner/work/_actions/Azure/functions-action/v1/node_modules/@azure/storage-blob/dist/index.js:24336:32)
    at WebsiteRunFromPackageDeploy.<anonymous> (/home/runner/work/_actions/Azure/functions-action/v1/lib/publishers/websiteRunFromPackageDeploy.js:27:70)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/Azure/functions-action/v1/lib/publishers/websiteRunFromPackageDeploy.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/_actions/Azure/functions-action/v1/lib/publishers/websiteRunFromPackageDeploy.js:4:12)
    at WebsiteRunFromPackageDeploy.execute (/home/runner/work/_actions/Azure/functions-action/v1/lib/publishers/websiteRunFromPackageDeploy.js:23:16)
    at ContentPublisher.<anonymous> (/home/runner/work/_actions/Azure/functions-action/v1/lib/handlers/contentPublisher.js:25:68)
    at Generator.next (<anonymous>)
```

If I manually append `EndpointSuffix=core.windows.net` to `AzureWebJobsStorage` in the Azure Portal deployment works fine.

**Comment by sindkor** [comment]
A workaround seems to be to set the `AzureWebJobsStorage`-parameter directory in `appSettingsKeyValuePairs` and unset `storageAccountResourceId`.

```bicep
var storageAccountConnectionString = 'DefaultEndpointsProtocol=https;AccountName=${storage.outputs.name};AccountKey=${listKeys(resourceId('Microsoft.Storage/storageAccounts', storageAccountName), '2023-01-01').keys[0].value};EndpointSuffix=${environment().suffixes.storage}'

(...)

AzureWebJobsStorage: storageAccountConnectionString
```

This might not work if you're configuring slots, as it also seems to use the `storageAccountResourceId`-parameter. Additionally, there might also be issues if the storage account doesn't already exists when the listKeys()-function is ran.

**Comment by tsc-buddy** [comment]
Hi There - Thanks for logging this issue. We shall triage this wc 8th July.
